name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: django-k8s
    steps:
      - uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 


      - name: Build the Docker image
        # working-directory: .
        run: |
          docker build -f Dockerfile \
              -t elghibaomar/fastapi-k8s-web-engagement:latest \
              -t elghibaomar/fastapi-k8s-web-engagement:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
              .

          
      
      - name: Docker Push
        run: docker push elghibaomar/fastapi-k8s-web-engagement --all-tags

      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}

      - name: Update Deployment image
        run: |
          kubectl set image deployment/fastapi-k8s-web-engagement-deployment fastapi-k8s-web-engagement=elghibaomar/fastapi-k8s-web-engagement:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
          

      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/fastapi-k8s-web-engagement-deployment




      